### ISSUE TITLE
OpenLayers version "3" word should be removed

### ISSUE THREAD

**Issue by sanak** [pgRouting/workshop#36]
The latest OSGeoLive 12 image's OpenLayers version is already 4.6.5,
and application path is not `/ol3/` but `/openlayers/`, so the words
`OpenLayers 3` or `ol3` should be changed to `OpenLayers` (or `OpenLayers (>=3)`) or `openlayers`.

![osgeolive12_ol](https://user-images.githubusercontent.com/629923/46773903-c0213880-cd3a-11e8-82c3-f1f5c817ddbc.png)

**Comment by dkastl** [comment]
@sanak , I made a pull request to change the naming. Not sure, if someone needs to review it first to be able to merge. However, I didn't want to merge myself, because I first would like to reconfirm, that this doesn't cause any issues with the translation files, especially because I renamed a file.

@cvvergara , I forgot how to update the POT files and Transifex. If the pull request does not cause troubles, feel free to merge it.
